### ISSUE TITLE
Using ie8 builds with other Angular Libraries

### ISSUE THREAD

**Issue by ktwrenn** [fergaldoyle/angular.js-ie8-builds#11]
In addition to the base angular library, I'm also using various other libraries that rely on angular (e.g. angular-animate, angular-route, etc.). Since the package name is different, the bower install of the other components fails due to the non-existent "angular" package. Do you have a suggestion on how to get around this without having to load angular twice in the bower install?

**Comment by fergaldoyle** [comment]
Does this work?

   // bower install with local name "angular"
   bower install angular=angularjs-ie8-build

**Comment by ktwrenn** [comment]
Do you know how to do this using the bower.json? I couldn't find an override for the package names. 

--
Kyle T. Wrenn

**Comment by fergaldoyle** [comment]
I ran `bower install angular=angularjs-ie8-build --save` and in `bower.json` the result was

      "dependencies": {
        "angular": "angularjs-ie8-build#~1.3.15"
      }

**Comment by f0def** [comment]
This worked for me

**Comment by ktwrenn** [comment]
This is perfect. Thank you!
