### ISSUE TITLE
Angular 1.4

### ISSUE THREAD

**Issue by truongsinh** [fergaldoyle/angular.js-ie8-builds#13]
Hi, great repo. Do you plan to support 1.4 too?

**Comment by fergaldoyle** [comment]
Now that 1.4 is out of beta, I'll take a look to see what effort might be required.

**Comment by truongsinh** [comment]
Well, I believe 1.4 has been beta for long enough, and GM waso already released yesterday http://angularjs.blogspot.fi/2015/05/angular-140-jaracimrman-existence.html?m=1

**Comment by truongsinh** [comment]
(Y)
)

**Comment by andriasang** [comment]
I updated the Angular 1.4 release with the first part of the 1.3.15 angular.js-ie8-builds release (as well as the last line, which adds ng-hide declarations to the head) and while I have yet to thoroughly test, everything seems to be working in IE8.

**Comment by fergaldoyle** [comment]
1.4.0 released
