### ISSUE TITLE
Error in line 1198

### ISSUE THREAD

**Issue by frisco82** [fergaldoyle/angular.js-ie8-builds#14]
I am getting an error during angular first load on line 1198, looking at the stack trace it seems it is injecting some styles during initialization.

![2015-05-29 12_54_44-herramientas de desarrollo](https://cloud.githubusercontent.com/assets/487098/7881308/f6bcc35e-0601-11e5-8d21-382259422044.png)
I am using current ES5-Shim 4.1.4 and Jquery 1.11.3 and the example in the repo loads without errors.
I can provide the files if needed as I was just porting the angularJS tutorial to use Angular for IE8.

**Comment by fergaldoyle** [comment]
Do you still have issues with this? Please send files if so.
