### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by Vexez** [fergaldoyle/angular.js-ie8-builds#19]
Error: Unexpected call to method or property access.
```
<md-select>
<md-option>
```
Not sure if its because this build is not compatible with Angular Material?

**Comment by Vexez** [comment]
Included these...

```
	<!--[if IE]>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.0.5/es5-shim.min.js"></script>
		<script src="/scripts/lib/angular-1.4.0.ie8.min.js"></script>
		<script>
	        document.createElement('md-input-container');
	        document.createElement('md-select');
	        document.createElement('md-option');

	        // Optionally these for CSS
	        document.createElement('md:select');
	        document.createElement('md:option');
      </script>
	<![endif]-->
```

**Comment by fergaldoyle** [comment]
Do you get the error on modern browsers or just IE8?
On 24 Aug 2015 9:47 am, Vexez <notifications@github.com> wrote:Included these...

**Comment by Vexez** [comment]
Just IE8
Everything works fine on IE11 and Chrome

**Comment by fergaldoyle** [comment]
I'd imagine material design itself uses some JS IE8 doesn't like. Probably using a reserved word with dot notation. See the readme of this repo with steps you could take to fix it.
On 24 Aug 2015 10:15 am, Vexez <notifications@github.com> wrote:Just IE8
Everything works fine on IE11 and Chrome

**Comment by Vexez** [comment]
Yup I saw that and searched thru angular material js.
It is already using ["catch"] in all cases by default.
There's only one finally that isn't dot notation, try {} finally {}

Not just md-select and md-option showing error, basically the entire angular material doesnt seem to be working...

Just want to double check here if it's currently supporting angular material, or may be some issues I'm not aware of that could be fixed easily, if not I will need to consider redesigning using other methods.

Thanks in advance.
