### ISSUE TITLE
Proper use of this library

### ISSUE THREAD

**Issue by gamedevhelper** [fergaldoyle/angular.js-ie8-builds#20]
I am a bit confused about the purpose of this library.  

Can we generate a project with popular scaffolding tools like https://github.com/yeoman/generator-angular (1.4) then just drop this version of Angular build and it will work with IE8 (tried and didn't work so far)

-or-

We need to create a Angular 1.2 app first then drop in this replacement package to use 1.4 like features?

**Comment by fergaldoyle** [comment]
Your first approach would be the correct approach. You should be able to create an Angular app with official 1.4, and allow it work in IE8, replace official 1.4 with with the build from this repo and add jQuery and ES5 shim

**Comment by gamedevhelper** [comment]
I will try this again and if successful I will create an arch type example and put it in git hub.
