### ISSUE TITLE
Any plans for 1.3.15+ IE8-compatible release?

### ISSUE THREAD

**Issue by CNBorn** [fergaldoyle/angular.js-ie8-builds#23]
In these releases some critical bugs are being fixed such as IE9 redirect loop bug is fixed in 1.3.17. It would be nice to have these releases as well.

**Comment by fergaldoyle** [comment]
Added a folder with 1.3.20
https://github.com/fergaldoyle/angular.js-ie8-builds/tree/master/1.3.x

**Comment by CNBorn** [comment]
@fergaldoyle Thanks for your work! but could you tag a separate version for 1.3.x and publish on npm? Otherwise it is not easy to use it unless a hard-copy. Thanks in advance

**Comment by fergaldoyle** [comment]
Tagged and published, `npm i angularjs-ie8-build@1.3.20`
