### ISSUE TITLE
How to use this vesion with angular-route and other angular modules?

### ISSUE THREAD

**Issue by batchu** [fergaldoyle/angular.js-ie8-builds#25]
How to use this vesion with angular-route and other angular modules?

As soon as I introduce angular-route.js (v1.40 consistent with the current version of angular.js-ie8-builds) it breaks IE8. Is this expected behavior and how can I fix it?

**Comment by fergaldoyle** [comment]
angular-route.js @ 1.40 may have some code or syntax that doesn't work with IE8.  Your options are to try and find those issues and resolve if easily fixed (see readme) or use an older version of angular-route.js
