### ISSUE TITLE
Support for controllerAs in directive definition object (DDO)?

### ISSUE THREAD

**Issue by alight-eskillz** [fergaldoyle/angular.js-ie8-builds#26]
Hello,

I have simple DDOs that specify the controller and controllerAs properties.  I then use angular.bootstrap to initialize the container modules after all other app initialization is complete.  That works well in newer browsers with Angular 1.4+, but it doesn't work with this Angular 1.4 IE8 build (in IE 8).  Have you successfully used controllerAs with your custom build, or do your apps avoid that and use the ng-controller directive instead?

Thanks.

**Comment by fergaldoyle** [comment]
I haven't actually used Angular to develop anything in a long time. Can you whip up an example of controllerAs usage?

**Comment by MarkRBM** [comment]
we are using controllerAs with this build back to ie8 without problems

**Comment by alight-eskillz** [comment]
Thank you, I also wasn't able to reproduce the issue in a simple example that uses controllerAs, angular.bootstrap, and $emit.  Now, I just need to figure out the differences between the working simple example and the broken application.
