### ISSUE TITLE
Compatibility with libraries?

### ISSUE THREAD

**Issue by paolopan83** [fergaldoyle/angular.js-ie8-builds#4]
How will this work with Angular based libraries angular-ui, angular-translate or any other library? Do they break if they use promise.catch?

**Comment by fergaldoyle** [comment]
Any library / code (Angular based or not) will cause IE8 to throw errors if a reserved word is used as an object property, e.g. `.catch`   `.delete`   `.finally`

So it would be up to you to look out for that if using modern libraries with IE8. If you come across it, you'll have to go into the source of the library and change from dot notation to bracket notation where those reserved words are used.  It's relatively easy to do with a find and replace. There may even be a grunt / gulp task to do it for you.

**Comment by rockallite** [comment]
I think [UglifyJS2](https://github.com/mishoo/UglifyJS2) will do this for you, which will automatically convert dot notations of reversed keywords to bracket notations, as soon as you **DO NOT** provide the ```--screw-ie8``` option. (See the source [here](https://github.com/mishoo/UglifyJS2/blob/master/lib/parse.js#L47) and [here](https://github.com/mishoo/UglifyJS2/blob/master/lib/compress.js#L2465).)

So you can easily find a grunt / gulp task for that.
