### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Ir1sh** [fergaldoyle/angular.js-ie8-builds#6]
Have you considered setting up a facility to receive donations? We would like to support this fork any way we can if you are open to it.

**Comment by fergaldoyle** [comment]
Not sure I could give the commitment required if there's money involved. Also I don't know how I'd feel about profiting off the back of everyone else who worked to make Angular. I merely merge the latest commits, check to see anything that may break IE8 and sprinkle some shims here and there.
