### ISSUE TITLE
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference

### ISSUE THREAD

**Issue by emmansun** [fergaldoyle/angular.js-ie8-builds#7]
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
File: angular.js, Line: 27, Column: 3

code:
  // ie8 ftw...

  // ------ XMLHttpRequest.onload ------
  // monkey patch XMLHttpRequest to make IE8 call onload when readyState === 4
  var sendFn = XMLHttpRequest.prototype.send;

**Comment by fergaldoyle** [comment]
This seems to happen in corporate environments where administrators have turned off XMLHttpRequest in Internet Explorer settings.

I'll try to see is there any workaround.

**Comment by fergaldoyle** [comment]
Here's shim to allow XMLHttpRequest exist when it is disabled in IE8 advanced settings. I'll include it in the next release, for now before add it before angular in your app to fix your above problem:

    if (!window.XMLHttpRequest) {
      //console.log('XMLHttpRequest not enabled');

      window.XMLHttpRequest = function () {
        var xmlhttp = new ActiveXObject('Microsoft.XMLHTTP'),
          out = {
            isFake: true,
            send: function (a) {
              return xmlhttp.send(a);
            },
            open: function (a, b, c, d, e) {
              return xmlhttp.open(a, b, c, d, e);
            },
            abort: function () {
              return xmlhttp.abort();
            },
            setRequestHeader: function (a, b) {
              return xmlhttp.setRequestHeader(a, b);
            },
            getResponseHeader: function (a) {
              return xmlhttp.getResponseHeader(a);
            },
            getAllResponseHeaders: function () {
              return xmlhttp.getAllResponseHeaders();
            },
            overrideMimeType: function (a) {
              return xmlhttp.overrideMimeType(a);
            }
          };

        xmlhttp.onreadystatechange = function () {
          out.readyState = xmlhttp.readyState;

          if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
            out.status = xmlhttp.status;
            out.responseText = xmlhttp.responseText;
            out.responseXML = xmlhttp.responseXML;
            out.statusText = xmlhttp.statusText;

            if (out.onload) {
              out.onload.apply(this, arguments);
            }
          }

          if (out.onreadystatechange) {
            out.onreadystatechange.apply(this, arguments);
          }

        };

        return out;

      };
    }

**Comment by fergaldoyle** [comment]
Fixed with latest release.
