### ISSUE TITLE
routeProvider doesn't appear to work...

### ISSUE THREAD

**Issue by KyleMcNutt** [fergaldoyle/angular.js-ie8-builds#8]
Since $locationProvider.html5Mode has to be false for IE8, there will always be #'s in the Paths for IE8. For example...

    http://localhost:8000/app/#/landing

Which means that the $routeProvider needs to look something like the following....

    $routeProvider.when('/#/landing', {
                templateUrl: 'views/landing.html',
                controller: 'landingCtrl'
    });

But for some reason this doesn't work when testing with IE8, I was wondering if this library handles $routeProvider differently? Or if maybe it's not working?

Thank you!

**Comment by fergaldoyle** [comment]
You should be able to just omit the starting "/#", e.g:

    $routeProvider.when('/landing', {
            templateUrl: 'views/landing.html',
            controller: 'landingCtrl'
    });

**Comment by KyleMcNutt** [comment]
I tried that as well, and the `landingCtrl` never gets loaded.

**Comment by fergaldoyle** [comment]
I have a kitchen sink page where I test this fork with IE8 and the ngRoute works fine.  Are you using ngRoute from the matching version of angular, e.g. 1.3.14?

**Comment by KyleMcNutt** [comment]
I was able to solve this problem by including `document.createElement('ng-view')` as is described in [this](https://code.angularjs.org/1.2.28/docs/guide/ie) IE Compatibility document.

**Comment by KyleMcNutt** [comment]
Thanks again for your help @fergaldoyle you have made a fantastic project here!
