### ISSUE TITLE
An example that uses angular.js-ie8-builds

### ISSUE THREAD

**Issue by asafyat** [fergaldoyle/angular.js-ie8-builds#9]
The project sounds interesting I have been looking for a while for a solution angular and IE8

Do you have an example that uses angular.js for IE8 it will be really helpful for me.

Thanks

**Comment by fergaldoyle** [comment]
There's not that much you have to do differently, there's just a few rules to follow to make your life easier when developing with IE8 in mind.

I've updated the readme with more IE8 considerations and also added a simple example app.
